version: "3.9"

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB:       CarManagementDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"

volumes:
  postgres_data: